services:
  postgres:
    restart: always
    ports: !override []

  app-blue:
    image: tuwumeu420/sportsclub:latest
    restart: always
    environment:
      - DEBUG=False
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

  app-green:
    image: tuwumeu420/sportsclub:latest
    restart: always
    environment:
      - DEBUG=False
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

  nginx:
    restart: always
    ports:
      - "80:80"
    # - "443:443" POSSIBLE IMPLEMENTATION IF SSL
