# docker-compose.production.yml

services:
  postgres:
    restart: always
    # Esto asegura que se limpie cualquier puerto del original
    ports: []

  app-blue:
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

  app-green:
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

  nginx:
    restart: always
    # El !override es la clave: borra el 8000 y pone solo el 80
    ports:
      - "80:80"
    # - "443:443"
