name: Docker Publish

on:
# ONLY RUNS IF ci.yml COMPLETED SUCCESSFULLY ALL ACTIONS
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dockerhub
    if: ${{ github.event.workflow_run.conclusion == 'success' && (startsWith(github.event.workflow_run.head_branch, 'v') || github.event.workflow_run.head_tag != '') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Extract Docker tag
        id: tag
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/sportsclub
          tags: |
            type=raw,value=${{ github.event.workflow_run.head_branch }}
            type=raw,value=latest
            type=sha

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/app/Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.tags }}
          labels: ${{ steps.tag.outputs.labels }}
